kudago_spb:
  target: local
  outputs:
    local:
      type: postgres
      host: "{{ env_var('PGHOST', '127.0.0.1') }}"
      port: 55432
      user: "{{ env_var('PGUSER', 'postgres') }}"
      password: "{{ env_var('PGPASSWORD', '') }}"
      dbname: "{{ env_var('PGDATABASE', 'kudago_dwh') }}"
      schema: analytics_candidate
      threads: 2
